server:
  port: 28080
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://planit-management.cvvjqr2echzv.ap-northeast-2.rds.amazonaws.com:3306/spring-react-security
    username: ENC(i24qGzDGEvQSc/4P35W6Fg==)
    password: ENC(PfM0DZBrCdKWmr7TyDjqBeKwDYnGBdnG)
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(SYYnG6BUHp6b7uqBWyNqPowTkiDKamrLMtrMM5xiMfQ=)
    password: ENC(MTkVWyIDcFEfK9MpL8qZdFngWA5G1Z4tL8PKE0waSlQ=)
    properties:
      mail:
        smtp:
          auth: true
          timoout: 5000
          starttls:
            enable: true
  thymeleaf:
    enabled: false
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace
yeboong:
  log:
    path: ./logs/spring-react-security.log
decorator:
  datasource:
    p6spy:
      enable-logging: true
